use_frameworks!

platform :ios, '9.3'

target 'BreinifyApi_Tests' do
  pod 'BreinifyApi'
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '2.3'  ## or '3.0'
      end
    end
  end
  
end
